name: GitHub Actions Runner
version: "1.0.5"
slug: github-runner
description: Self-hosted GitHub Actions runner for your repositories
url: https://github.com/fzoll/ha-addons
arch:
  - aarch64
  - amd64
startup: services
boot: auto
init: false
options:
  access_token: ""
  repos: []
  runner_name: ha-runner
  labels: self-hosted,linux,arm64
schema:
  access_token: password
  repos:
    - str
  runner_name: str
  labels: str
